### ISSUE TITLE
Play the audio with seek position time greater than zero makes it play a bit of their beginning

### ISSUE THREAD

**Issue by YuriHeupa** [brianwernick/PlaylistCore#12]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- PlaylistCore version: `1.1.0`
- Device OS version: `5.0.2`
- Devide Manufacturer: `HTC`
- Device Name: `One X`
###### Reproduction Steps
1. Change the seekPosition field in method `playlistManager.play(0, false);`  in AudioPlayerActivity.java to any value greater than 0, i.e.: playlistManager.play(10000, false); 
2. Wait audio to play.
###### Expected Result

Start playing the audio exactly at the given seekPosition
###### Actual Result

After the audio loads it starts from 0 and play a little ms than jumps to seekPosition, in the meantime I can hear the audio plays a bit of their beginning.

**Comment by YuriHeupa** [comment]
Just for note, I'm streaming an audio at the same time as i'm downloading in another context, so after the download completes I call the `play()` method from the playlistmanager to "refresh" the audio, which will trigger the `playAudioItem()` from the PlaylistServiceCore.java and consequently it will call my implemented method `isDownloaded()`, which now will return true and will start playing from a local resource, but for this I really need this bug to be fixed, because when I "change" from remote to local I want to continue playing from the same time it was playing, without interruption, it would be nicely to see this feature implemented in this nice library, and it would be the "main" feature of my app.

**Comment by brianwernick** [comment]
Fixed in https://github.com/brianwernick/PlaylistCore/commit/e2feb8f94ce9f9f68b9f265d1d9326791371badb

**Comment by YuriHeupa** [comment]
Do you have plans to release this in gradle repo soon?

**Comment by brianwernick** [comment]
Yeah, I was planning on releasing this weekend (I have another issue written down on paper at home that I want to fix before a release)
