### ISSUE TITLE
Show notification only when app is in foreground

### ISSUE THREAD

**Issue by YuriHeupa** [brianwernick/PlaylistCore#14]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

**Is possible to make the player notification only show when the apps goes to foreground state?**

One of the reasons to do it Is because I only want to call methods like `onLargeNotificationImageUpdated()` and `onRemoteViewArtworkUpdated()`  when the app is in foreground, because these methods are a little slow to execute and my application is skipping 100+ frames every time I change the current playing item. 

Just for note, i'm using Glide instead Picasso (That was used in demo) to load bitmaps on notification update methods, but I think that's not the problem, i.e.:

``` java

    @Override
    protected void updateLargeNotificationImage(int size, MediaItem playlistItem) {
        Glide.with(this).load(playlistItem.getThumbnailUrl()).asBitmap()
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                        largeNotificationImage = resource;
                        onLargeNotificationImageUpdated();
                    }

                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {
                        super.onLoadFailed(e, errorDrawable);
                        largeNotificationImage = null;
                    }
                });
    }

    @Override
    protected void updateRemoteViewArtwork(MediaItem playlistItem) {
        Glide.with(this).load(playlistItem.getArtworkUrl()).asBitmap()
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                        remoteViewArtwork = resource;
                        onRemoteViewArtworkUpdated();
                    }

                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {
                        super.onLoadFailed(e, errorDrawable);
                        remoteViewArtwork = null;
                    }
                });
    }
```

**Comment by brianwernick** [comment]
Maybe this is just a confusion of terms but when the media is in playback the service is foreground.

As far as the image loading goes, what device are you seeing this on (OS version, device name, etc.)?  I use glide in a couple of apps and haven't seen a UI issue like this, though I am making sure to call `.override(size, size)` when loading the images so that may be part of what you are seeing

**Comment by YuriHeupa** [comment]
- PlaylistCore version: `1.1.1`
- Device OS version: `5.0.2`
- Devide Manufacturer: `HTC`
- Device Name: `One X`

But there's any way with this library to customize the notification visiblity? Like showing only if the app is minimized?

**Comment by brianwernick** [comment]
So there is the `PlaylistServiceCore` which handles most of the playlist functionality except the notification and remote views (such as lock screen) that you can extend from (the `BasePlaylistService` extends this).  However that is the worst case senario; I would assume that you can extend the `BasePlaylistService` to do what you want using the `updateRemoteView()` and `updateNotification()` methods but can't say for certain without looking in to it more

**Comment by YuriHeupa** [comment]
So I will implement my own handler extending the BasePlaylistService, thanks for pointing the right direction.
