### ISSUE TITLE
Call invokePausePlay() while audio is on PREPARING state

### ISSUE THREAD

**Issue by YuriHeupa** [brianwernick/PlaylistCore#15]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- PlaylistCore version: `1.1.1`
- Device OS version: `5.0.2`
- Devide Manufacturer: `HTC`
- Device Name: `One X`
###### Reproduction Steps
1. Start a playback from a remote file (url streaming)
2. While file is in PREPARING state call `invokePausePlay()`
###### Expected Result

When the file exits PREPARING state right before `invokePausePlay()` was called, the media should start paused.
###### Actual Result

I get the following logs after calling `invokePausePlay()` while state is PREPARING:

```
D/onPlaybackStateChanged() called with: playbackState = [PREPARING]
D/MediaControlsHelper: update, controller is null ? false
D/PlaylistManager: Called invokePausePlay()
E/MediaPlayer: start called in state 4
E/MediaPlayer: error (-38, 0)
D/onPlaybackStateChanged() called with: playbackState = [PLAYING]
D/MediaControlsHelper: update, controller is null ? false
E/MediaPlayer: Error (-38,0)
D/PlaylistServiceCore: Retrying audio playback.  Retry count: 1
D/MediaPlayer: Couldn't open file on client side, trying server side
D/MainActivity: onPlaybackStateChanged() called with: playbackState = [PREPARING]
D/MediaControlsHelper: update, controller is null ? false
D/MediaService: performOnMediaCompletion() called 
```

Like the demo app, my `performOnMediaCompletion()` have this:

``` java
performNext();
immediatelyPause = false;
```

In my application when the user press the PLAY button on a stream file, the button instantly changes to a PAUSE button, even if the audio is still not playing, just preparing, and the user can hit the pause in this state.
In my case if the user does this, the performOnMediaCompletion() will be called and the next file in playlist will start playing, and I wanted the performOnMediaCompletion not to be called, but I think this is how Android MediaPlayer works if I call play while the file is being prepared, so searching a little more about this I've found that this method in `PlaylistServiceCore.java`, 

``` java
protected void performPlayPause() {
    if (isPlaying()) {
        performPause();
    } else {
        performPlay();
    }
}
```

This method is triggered when I call `invokePausePlay()`, which checks if the audio is playing with the method `MediaPlayer.isPlaying()`, but the audio is in PREPARING state, so it will return false and the `performPlay()` will be called throwing these errors:

```
E/MediaPlayer: start called in state 4
E/MediaPlayer: error (-38, 0)
```

That's the reason `onPlaybackStateChanged()` is called with: `playbackState = [PLAYING]` right after `performPlayPause()`

I think something should be implemented in performPlayPause() to check if the audio is in PREPARING state and handles this case.

**Comment by brianwernick** [comment]
Sorry for the late reply, I think the email got lost.

Because PlaylistCore doesn't know which media player is being used (native android, custom) I left this up to the implementing APIs to handle because some I've ran across already handle them (e.g. store the requested state until they are ready)

That being said, I should probably update the notification to have a loading state that doesn't display the next, previous, or play/pause buttons.

**Comment by pratheepchowdhary** [comment]
Thank u sir

**Comment by brianwernick** [comment]
The default notification has been updated in the 2.0 branch to handle loading states (i.e. disable the play/pause) button until media is loaded.
