### ISSUE TITLE
Error while to trying to download playlistcore package

### ISSUE THREAD

**Issue by thomasdola** [brianwernick/PlaylistCore#2]
hi 
am trying to download the playlistcore package but error
`Error:(36, 13) Failed to resolve: com.devbrackets.android:playlistcore:1.0.0`

**Comment by brianwernick** [comment]
This is a temporary issue with the library not being included in jcenter yet (there is a manual review process).  In the meantime you can include the specific maven repo that contains the aar with 

``` gradle
repositories {
    maven {
        url "https://dl.bintray.com/brianwernick/maven"
    }
}
```

NOTE: previously it has only taken about 24 hours for the library to be included on jcenter (this only occurs when you request to be included on jcenter, not when uploading new versions)

**Comment by brianwernick** [comment]
PlaylistCore should now be in jcenter so you can use the standard 

``` gradle
repositories {
    jcenter();
}
```
