### ISSUE TITLE
how to play local music file?

### ISSUE THREAD

**Issue by BadDeveloper2022** [brianwernick/PlaylistCore#20]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- PlaylistCore version: `1.0.1`
- Device OS version: `6.0`
- Devide Manufacturer: `Huawei`
- Device Name: `Nexus 6P`
###### Reproduction Steps
1.

**Comment by brianwernick** [comment]
PlaylistCore itself doesn't handle the playback of the audio or video, this is left up to the `AudioPlayerApi` and `VideoPlayerApi` so the answer may change depending on those. However, most media players will allow you to pass in a `URI` for the file, which would be the absolute path (e.g. `/data/data/com.devbrackets.android.playlistcoredemo.Files.music.smooth_criminal.mp3`). For playlist core the [IPlaylistItem#getMediaUrl()](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/manager/IPlaylistItem.java#L29) should return the absolute path

**Comment by BadDeveloper2022** [comment]
![image](https://cloud.githubusercontent.com/assets/7404699/17798706/4c9eb3ee-6606-11e6-8ea7-0ab46ca6f35b.png)
![image](https://cloud.githubusercontent.com/assets/7404699/17798723/78721b46-6606-11e6-87da-bb46db14818e.png)
