### ISSUE TITLE
Update buttons displayed at notifications section

### ISSUE THREAD

**Issue by gustiacosta** [brianwernick/PlaylistCore#23]
When we have just one media item in our PlayListManager, the notification section displays just the play/pause button, that's ok, but how can we invoke to update the displayed buttons once we add a new media item to que queue list?? it there any way to do this?? for example to display the "Next" button when the new media item is added

-Using lib PlaylistCore version: `1.1.1`

**Comment by brianwernick** [comment]
In the class that extends `PlaylistServiceCore` or `BasePlaylistService` you can call [updateNotification()](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L239)

**Comment by gustiacosta** [comment]
i will try it and let you know! thank you!!
