### ISSUE TITLE
Update buttons displayed at notifications section

### ISSUE THREAD

**Issue by gustiacosta** [brianwernick/PlaylistCore#26]
Sorry for re-open this question about when we have just one media item in our PlayListManager, the notification section displays just the play/pause button.

I was trying to reach the `updateNotification()` method from every class i used but i got no luck, because it is at MediaService level - (or i dont know how to expose it)

Is it possible to expose it at the ListPlaylistManager level?? the class the extends `BasePlaylistManager`. or can you guide me to reach that method please??

I have created the following method on a new class that extends the "`ListPlaylistManager`"

```
public void addItem(I item) {
        if (this.items == null) {
            this.items = new ArrayList<>();
        }

        this.items.add(item);

        //noinspection SynchronizeOnNonFinalField
        synchronized (this.items) {
            this.items.notify();
        }
    }
```

it works fine but i'd like to update the notification right from here after the item was added or call `PlayListManager.updateNotification();`

help me please!!

-Using lib PlaylistCore version: 1.1.1

**Comment by brianwernick** [comment]
[updateNotifcation()](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L240) is `protected`, as such it can only be accessed by classes the extend `PlaylistServiceCore`. 

If you want to be able to control that via the `ListPlaylistManager` then you will need to create a custom `ACTION_*` constant to communicate with the playlist service and override [handleRemoteAction(...)](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L1098) (make sure to call `super.handleRemoteAction(...)`); sending the `ACTION_*` via a pending intent.

see [create `nextPendingIntent`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/manager/BasePlaylistManager.java#L680) and [send `nextPendingIntent`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/manager/BasePlaylistManager.java#L604) for an example

e.g.

``` java
@Override
protected boolean handleRemoteAction(String action, Bundle extras) {
    boolean handled = super.handleRemoteAction(action, extras);
    if (!handled && action.equals(ACTION_UPDATE_NOTIFICATION)) {
        updateNotification();
        handled = true;
    }

    return handled;
}
```
