### ISSUE TITLE
Audio URL not working

### ISSUE THREAD

**Issue by mitesh21** [brianwernick/PlaylistCore#28]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - PlaylistCore version: `1.1.1`

###### Reproduction Steps
When i play below URL it's working in your code. but works in VLC player.
http://demo.eonssofttech.co/muzica/assets/uploads/album_data/el-perdedor.mp3
Above URL works in iOS,Web and BB. 

This URL works
http://demo.eonssofttech.co/muzica/assets/uploads/album_data/Six-Days.mp3

###### Actual Result
Showing me UNKNOWN_ERROR which playing give URL.

Please check why this Audio not working.

**Comment by brianwernick** [comment]
PlaylistCore doesn't perform the actual playback of media, instead it takes an API implementation to perform the playback. Whatever error you are receiving is due to the AudioApi implementation you provide.

**Comment by mitesh21** [comment]
@brianwernick  : not get your point. can you please share what should be issues?

I tried exoPlayer and it's working fine.

Can you please make relevant changes which should works perfectly.

**Comment by brianwernick** [comment]
See [Demo AudioApi.java](https://github.com/brianwernick/PlaylistCore/blob/master/demo/src/main/java/com/devbrackets/android/playlistcoredemo/helper/AudioApi.java) for an example. The playback issue you mentioned is not part of `PlaylistCore` it is due to the implementation (similar to the linked one) for your `AudioPlayerApi`

**Comment by mitesh21** [comment]
@brianwernick  i already follow your code and still showing error.

Have you check Audio URL in app and it's working ? As in exoPlayer  it's works perfect.
Guide me how to play given audio file and all type of audio file.

**Comment by brianwernick** [comment]
Oops didn't mean to lock the thread... 

Again; `PlaylistCore` doesn't handle the actual media playback, that is left up to the user (you) to pass in an implementation of the `AudioPlayerApi` that works as expected. The demo uses the Android `MediaPlayer` as the implementation, it sounds like you need to swap it out with an ExoPlayer implementation instead (see the [ExoMedia demo AudioApi.java](https://github.com/brianwernick/ExoMedia/blob/master/demo/src/main/java/com/devbrackets/android/exomediademo/playlist/AudioApi.java) for an example)
