### ISSUE TITLE
Async bitmap loading.

### ISSUE THREAD

**Issue by karimknaebel** [brianwernick/PlaylistCore#3]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

This is actually not a bug but a suggestion for an improvement. The only thing that's holding me back from using this lib in my app is, that I'm forced to return the Bitmaps synchronously.

EDIT: My bad, haven't seen that it's possible to manually initiate a notification update.

**Comment by brianwernick** [comment]
There are a few methods that will get called to inform you that you need to update the images (artwork, notification, etc.) which the `MediaService` in the demo shows.  

For example:
`updateRemoteViewArtwork(MediaItem playlistItem)` will get called when the artwork (used for the lockscreen, android wear, etc.) needs to be updated. 
In the demo app I use that to kick off an async image loader to retrieve the image.  Once it's retrieved in the [LockScreenTarget](https://github.com/brianwernick/PlaylistCore/blob/master/demo/src/main/java/com/devbrackets/android/playlistcoredemo/service/MediaService.java#L155) we store the image and inform the BasePlaylistService that the associated views need to be updated with `onLockScreenArtworkUpdated`

**Comment by karimknaebel** [comment]
Thx, I saw that too now. Sorry for posting this issue before I've properly inspected the code!
Great library btw!

**Comment by brianwernick** [comment]
No Problem, I'm glad you figured it out.

And I'm glad that I can help simplify playlists :)
