### ISSUE TITLE
How avoid skipping to next song on duration at 0

### ISSUE THREAD

**Issue by pratheepchowdhary** [brianwernick/PlaylistCore#34]
Hello Sir I wan to play song s continuous so placed perform next () in performon complete listener ()
From that time when I was pressing list view it skips to next song while clicks on play button and progress bar same happened so please tell me the code to clear this issue which I want place on perform on complete listener ()
Please help me sir thanking u sir in advance

**Comment by brianwernick** [comment]
Are you looking for _replay_ functionality or playing items in a list?  The latter is what the demo does

**Comment by pratheepchowdhary** [comment]
automatically play next song on song completed with out user interaction

**Comment by brianwernick** [comment]
See the demo app for an example then
