### ISSUE TITLE
Media Player state error when calling PlaylistManager.play() with a seek position greater than 0

### ISSUE THREAD

**Issue by AngelJedi** [brianwernick/PlaylistCore#36]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
PlaylistCore version `1.1.2`

Commit 906ab1f causes the wrong audio position in the playlist to play. When trying to play position 0 it increments the position by one causing the next item in the list to start playback instead.

**Comment by brianwernick** [comment]
I wonder if this is what #34 was trying to describe.

Anyways, reproduction steps:
  ~1. Play the 2nd-4th audio item in the demo~
  ~2. Back out of the player activity~
  ~3. Select the 1st item~
  * What I was seeing was a bug in the demo. @AngelJedi would you upload your reproduction steps

###### Expected Result:
  The 1st item plays correctly

###### Actual Result:
  The playlist resumes where it was previously playing

**Comment by AngelJedi** [comment]
It looks like I was in the wrong area for what was happening and I saw something out of place, but it wasn't the cause. 

The real culprit seems to be line #1227 of PlaylistServiceCore which calls performPause() in an invalid state on the media player if I pass a seekPosition other than 0 into the play() method of my playlist manager.

After calling that method the media player outputs these two lines into my log:

E/MediaPlayer: pause called in state 8, mPlayer(0x7f0758dac0)
E/MediaPlayer: error (-38, 0)

Then the onError method of the MediaListener is called, which tries to retry playback a number of times, each time causing a state error on the media player, and then eventually the next item is queued up for playback because of the error.
