### ISSUE TITLE
shuffle and random play

### ISSUE THREAD

**Issue by piseysen** [brianwernick/PlaylistCore#38]
When release shuffle and random play feature. I hope, it will release soon with example.

**Comment by brianwernick** [comment]
These haven't been something that was intended to be added by the library. See [performRepeat()](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L519) and [performShuffle()](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L529) for more information.
