### ISSUE TITLE
onPrepared() called twice after invokeNext() or invokePrevious()

### ISSUE THREAD

**Issue by AngelJedi** [brianwernick/PlaylistCore#39]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
 
After calling invokeNext() or invokePrevious() on the manager, the onPrepared listener receives two "prepared" callbacks for audio playback. I'm using an AudioPlayerApi identical to the one in the demo with ExoPlayer as the backing audio player. 

Expected Result:
Only one onPrepared() callback should occur.

Actual Result:
The first callback properly handles starting of the next audio item as expected, the second callback has the net effect of "pausing" the audio controls even though playback continues uninterrupted because of the if statement at the bottom of the startMediaPlayer() method that posts a PAUSED PlaybackState.

**Comment by brianwernick** [comment]
What version of `ExoMedia` were you seeing this with? If it was a `4.0.0-preview` then the issue was in `ExoMedia` itself (see https://github.com/brianwernick/ExoMedia/issues/444) and has been fixed in `4.0.1`
