### ISSUE TITLE
Resume to play automatically when OnSeek is completed

### ISSUE THREAD

**Issue by TonyTangAndroid** [brianwernick/PlaylistCore#4]
In **ExoMedia** _master_ demo, when we use the seekbar to drag the progress of a audio playback, it will first pause the playback and then start the seek. However, when the user stops tracking touch on the seek bar, it is supposed to resume the playback automatically. But in class 

`PlaylistServiceCore.java` method 

```
/**
     * Performs the functionality to end a seek for the current
     * media item.  This is called through an intent
     * with the {@link RemoteActions#ACTION_SEEK_ENDED}, through
     * {@link BasePlaylistManager#invokeSeekEnded(int)}
     */
    protected void performSeekEnded(int newPosition) {
        performSeek(newPosition);
    }
```

It did not resume to play the audio by executing the following statement.

`if (pausedForSeek) {
            performPlay();
            pausedForSeek = false;
        }`

I am not sure this is by design or an issue. I will send the pull request in 10 minutes to fix it if it is considerate as an issue.

**Comment by brianwernick** [comment]
It should start playback when the seek is finished (i.e. the `OnSeekComplete()` listener is informed of the change)  If it isn't then this is a bug.  

Though this may just be an issue in the `ExoMedia` demo where the ExoPlayer backed Audio (and Video) player doesn't inform the listener of the seek completion.  (I know that is the case on the 3.0 branch, but I don't know about master at the moment)

**Comment by TonyTangAndroid** [comment]
hold a moment. It turns out that I was using the demo from ExoMedia 3.0 branch to reproduce this issue. However, I was using the demo from PlaylistCore, it works okay. I will look into it right now and give you feedback. Sorry for raising a wrong potential alarm before confirming it.

**Comment by brianwernick** [comment]
That's fine.  I'm glad that you are paying attention to possible issues and bringing them up (even if it isn't an issue currently)

**Comment by TonyTangAndroid** [comment]
I have confirmed it. This issue could only be reproduced with the demo of ExoMedia branch 3.0 as it uses ExoPlayer which does not have the onSeekCompletion callback. I have created a pull request in fixing this issue. Please check it out and do let me know if there is other issue. You could use 

`compile 'com.github.TonyTangAndroid:PlaylistCore:1.0.2'
`

to test it with [jitpack](https://jitpack.io/) configuration on ExoMedia branch 3.0.

**Comment by brianwernick** [comment]
Because this is actually an issue with the ExoMedia 3.0 (dev) branch I'm going to close this.  Before ExoMedia 3.0 is released I will be adding the functionality to inform listeners of status changes (seek completion in this case)

**Comment by TonyTangAndroid** [comment]
Cool. Looking forward to the update of ExoMedia 3.0.

**Comment by brianwernick** [comment]
I have updated the ExoMedia 3.0 branch to correctly inform of seek completion (https://github.com/brianwernick/ExoMedia/pull/142)
