### ISSUE TITLE
how we replay the whole playlist?

### ISSUE THREAD

**Issue by Nardeep** [brianwernick/PlaylistCore#44]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - PlaylistCore version: `1.0.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by Nardeep** [comment]
I want to replay the playlist when playlist stop .

**Comment by brianwernick** [comment]
Listen for the item completion and compare the current index to the list size. If it's at the end wrap to the first item
