### ISSUE TITLE
Question: How to play the next track on Error

### ISSUE THREAD

**Issue by brian2694** [brianwernick/PlaylistCore#54]
Hello, I want to play the next song when retryCount == MAX_RETRY_COUNT 
I've tried modifiying  PlayListServiceCore

public boolean retryAudio() {
            if (currentItemIsType(BasePlaylistManager.AUDIO) && ++retryCount <= MAX_RETRY_COUNT) {
                Log.d(TAG, "Retrying audio playback.  Retry count: " + retryCount);
                playAudioItem();
                return true;
            }else{
                performNext();
                performPlay();
            }
            return false;
        }

This does not work. What I should do? Thks

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - PlaylistCore version: `1.1.3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Moto G4 Plus`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
You can override [`PlaylistServiceCore#performOnMediaError()`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L545) to instead seek the the next item if it is available. e.g.
```java
@Override
protected void performOnMediaError() {
    if (getPlaylistManager().isNextAvailable()) {
        performNext();
    } else {
        super.performOnMediaError();
    }
}
```

**Comment by brian2694** [comment]
This select the next song, I can see in my PlaylistFragment the next song selected, but does not start to play. It's paused

**Comment by brianwernick** [comment]
well, yeah. that's because we haven't told it to play after going to the next song. You can always do 
```java
//...
performNext();
immediatelyPause = false;
//...
```

**Comment by brian2694** [comment]
It works perfectly for me, thank you very much
