### ISSUE TITLE
Why don't have feature like version 1.1.3?

### ISSUE THREAD

**Issue by piseysen** [brianwernick/PlaylistCore#59]
Example:
performShuffle
performPrevious
performNext
performOnMediaCompletion

**Comment by brianwernick** [comment]
There's two parts to this; `performShuffle` never had any functionality inside the library other than the service/receiver setup so it was removed to avoid confusion and simplify library maintenance.
The other methods are delegated to the [`PlaylistHandler`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/playlisthandler/PlaylistHandler.kt) now with different names. Usually you will use the [`DefaultPlaylistHandler`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/playlisthandler/DefaultPlaylistHandler.kt) which handles the completion in [`onCompletion`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/playlisthandler/DefaultPlaylistHandler.kt#L222)

**Comment by piseysen** [comment]
Thanks for your answer.
