### ISSUE TITLE
is there a callback on the current audio playback completed

### ISSUE THREAD

**Issue by TonyTangAndroid** [brianwernick/PlaylistCore#6]
Hi there, just wondering if there is a callback on the current audio playback completed or not. I understand that there is a callback 

`public interface ProgressListener {

```
/**
 * Occurs when the currently playing item has a progress change
 *
 * @return True if the progress update has been handled
 */
boolean onProgressUpdated(@NonNull MediaProgress mediaProgress);
```

}
`

But it does not necessarily means that the current playback is completed. And sometimes it will be invalid to check the logic of the equation between `position` and `duration` because it won't be exactly the same if you are using ExoPlayer.

**Comment by brianwernick** [comment]
In the `BasePlaylistService` there is a method called [performOnMediaCompletion()](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L541) that you can override and perform the expected functionality (I normally call `performNext();`)

**Comment by TonyTangAndroid** [comment]
I have tried to `performNext();` it turns out that the audio will be changed but it did not automatically start the playback. I have to press the start button to play the audio. Is this expected?  I have tried to look into the source code and did not find a way to make it play automatically. Any hint, please?

**Comment by brianwernick** [comment]
This is because the `performNext();` persists the current playback state (which from completion is not playing).

If you want the media to play then you can set `immediatelyPause` to `false`.  e.g.

``` java
    @Override
    protected void performOnMediaCompletion() {
        performNext();
        immediatelyPause = false;
    }
```

**Comment by TonyTangAndroid** [comment]
It works. Much appreciated.
