### ISSUE TITLE
lack of pending intent notification 

### ISSUE THREAD

**Issue by Zevsus** [brianwernick/PlaylistCore#60]
- PlaylistCore version: `2.0.0`
 Good afternoon!
In the old version PlaylistCore 1.1.3  there was a simple setup pending intent notification , but now there is no.
How it can be configured now?

**Comment by brianwernick** [comment]
The [`DefaultPlaylistNotificationProvider`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/notification/PlaylistNotificationProvider.kt) has a field (or get method in Java) that needs to be overridden to specify the [`clickPendingIntent`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/notification/DefaultPlaylistNotificationProvider.kt#L49)

**Comment by Zevsus** [comment]
Thank you. I can not get it, but I did it using the Override DefaultPlaylistHandler.

**Comment by brian2694** [comment]
@Zevsus can you post your code? I want to do the same

**Comment by kazaky** [comment]
@brianwernick Can you explain in the (ExoMedia Demo) how to override the clickPendingIntent?
I can't seem to get it to work

**Comment by brianwernick** [comment]
Here's an example of an overridden [`DefaultPlaylistNotificationProvider`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/notification/PlaylistNotificationProvider.kt) that handles a custom `PendingIntent`
```kotlin
class AppPlaylistNotificationProvider(context: Context) : DefaultPlaylistNotificationProvider(context) {

    override val clickPendingIntent: PendingIntent?
        get() {
            //TODO return your pending intent here
            return createPendingIntent(MediaService::class.java, RemoteActions.ACTION_PLAY_PAUSE)
        }
}
```

Then when you create your `PlaylistHandler` (`DefaultPlaylistHandler` in the demo app) pass in the `AppPlaylistNotificationProvider`; e.g. in the Demo apps `MediaService`
```Java
        DefaultPlaylistHandler.Builder<MediaItem, PlaylistManager> builder = new DefaultPlaylistHandler.Builder<>(
                getApplicationContext(),
                getClass(),
                getPlaylistManager(),
                imageProvider
        );

        builder.setNotificationProvider(new AppPlaylistNotificationProvider(getApplicationContext()));
        return builder.build();
```
