### ISSUE TITLE
If the connection fails, the player switches three times to the next file.

### ISSUE THREAD

**Issue by Zevsus** [brianwernick/PlaylistCore#62]
Good evening! I would like to pause a connection error, and not switch to another file. Thank you in advance.

**Comment by brianwernick** [comment]
You can override [`onError`](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/playlisthandler/DefaultPlaylistHandler.kt#L228) in the `DefaultPlaylistHandler` to replace it with whatever you want to do on an error
