### ISSUE TITLE
Where to show a dialog warning if I want to check for mobile or wifi internet

### ISSUE THREAD

**Issue by nabil6391** [brianwernick/PlaylistCore#63]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

Hi I would like to allow media streaming only for wifi. In cases of mobile 3g internet, I would like to show a dialog box asking permission to allow to streaming using mobile data... Where should I put this mechanism

Thanks

**Comment by brianwernick** [comment]
This is something you'll have to handle in your service (and Activity for UI presentation). This isn't anything specific to this library so I'm closing the issue
