### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException

### ISSUE THREAD

**Issue by Zevsus** [brianwernick/PlaylistCore#64]
- PlaylistCore version: `2.0.0`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Huawei`
 - Device Name: `X2, P8 Lite`
Crash:
Fatal Exception: android.app.RemoteServiceException
Bad notification posted from package com.audio.app: Couldn't expand RemoteViews for: StatusBarNotification(pkg= com.audio.app user=UserHandle{0} id=2131230989 tag=null score=0 key=0|com.audio.app|2131230989|null|10133: Notification(pri=0 contentView= com.audio.app/0x109007f vibrate=null sound=null defaults=0x0 flags=0x72 color=0x00000000 category=transport actions=3 vis=PUBLIC))

Good afternoon! The application crashes when it is launched on some devices. I really hope for help from your side. Thank you for your work.

**Comment by brianwernick** [comment]
1. Does this happen in the Demo app as well?
2. Is the notification icon a bitmap/mipmap or a vector drawable?
3. Are any of the notification images null?

**Comment by Zevsus** [comment]
1. unfortunately I can not say, but this happens on some devices, I do not have this (
2. raster (add image asset - notification icons)
3. no
