### ISSUE TITLE
Support Intent.ACTION_MEDIA_BUTTON broadcasts.

### ISSUE THREAD

**Issue by Jovandine** [brianwernick/PlaylistCore#74]
Hello! Some apps use this approach to control play\pause of media players. 

for example:
       val downIntent = Intent(Intent.ACTION_MEDIA_BUTTON)
        val downEvent = KeyEvent(eventTime, eventTime, KeyEvent.ACTION_DOWN, KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE, 0)
        downIntent.putExtra(Intent.EXTRA_KEY_EVENT, downEvent)
        packageName?.let {
            downIntent.setPackage(packageName)
        }
        context.sendBroadcast(downIntent)

        val upIntent = Intent(Intent.ACTION_MEDIA_BUTTON)
        val upEvent = KeyEvent(eventTime+50, eventTime+50, KeyEvent.ACTION_UP, KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE, 0)
        upIntent.putExtra(Intent.EXTRA_KEY_EVENT, upEvent)
        packageName?.let {
            upIntent.setPackage(packageName)
        }
        context.sendBroadcast(upIntent)

or this question

https://stackoverflow.com/questions/40520094/android-unable-to-control-the-media-player-by-sending-the-broadcast-of-key-code

Can you please add support for this in your lib?

**Comment by brianwernick** [comment]
This is already handled in the `DefaultMediaSessionControlsReceiver` (see [`onReceive`](https://github.com/brianwernick/PlaylistCore/blob/0b5fe013c4a021eef29261fa3a864947690307dd/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/mediasession/DefaultMediaSessionControlsReceiver.kt#L38) and [`handleKeyEvent`](https://github.com/brianwernick/PlaylistCore/blob/0b5fe013c4a021eef29261fa3a864947690307dd/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/mediasession/DefaultMediaSessionControlsReceiver.kt#L67))

**Comment by Jovandine** [comment]
This function handleMediaButtonIntent works only if there is a service class in intent:
val mediaServiceClass = getServiceClass(intent, DefaultMediaSessionProvider.RECEIVER_EXTRA_CLASS)
But third party app, that want to control play\pause of any media app, can't pass service name there.
