### ISSUE TITLE
A quick question about PlaylistItemChange

### ISSUE THREAD

**Issue by TonyTangAndroid** [brianwernick/PlaylistCore#8]
Hi Brian, just for a quick question, the class `PlaylistItemChange`  does not necessarily means that the item being played has been changed from one song to another song. It just represents the current item being played? I had assumed that 'PlaylistItemChange' means that the item being played has been changed from one song to another song after you put your app into background. Thank you very much for writing this library, it has greatly helped me in working a sample media play app.

**Comment by brianwernick** [comment]
[onPlaylistItemChanged](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/listener/PlaylistListener.java#L36) is only called when the media item being played has changed.  The class [PlaylistItemChange](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/event/PlaylistItemChange.java) is used both as a utility to hold the current state, and an object to retrieve the current item with (see the demo `AudioPlayerActivity` when it is setting up the UI).
