### ISSUE TITLE
Android 12 Crash 

### ISSUE THREAD

**Issue by ChoHtetDev** [brianwernick/PlaylistCore#85]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - PlaylistCore version: `2.0.1`
 - Device OS version: `12`
 - Devide Manufacturer: `Google `
 - Device Name: `Pixel 4`
 
###### Reproduction Steps
Caused by java.lang.IllegalArgumentException
jp.co.hivelocity.glay.staging: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
android.app.PendingIntent.checkFlags (PendingIntent.java:375)

android.app.PendingIntent.getService (PendingIntent.java:686)
com.devbrackets.android.playlistcore.manager.BasePlaylistManager.createPendingIntent (BasePlaylistManager.kt:493)
com.devbrackets.android.playlistcore.manager.BasePlaylistManager.constructControlIntents (BasePlaylistManager.kt:469)
com.devbrackets.android.playlistcore.manager.BasePlaylistManager.<init> (BasePlaylistManager.kt:143)
com.devbrackets.android.playlistcore.manager.ListPlaylistManager.<init> (ListPlaylistManager.kt:30)
jp.co.hivelocity.glay.manager.PlaylistManager.<init> (PlaylistManager.java:66)
jp.co.hivelocity.glay.App.onCreate (App.java:84)

###### Expected Result
Pending Intent to be solved

**Comment by brianwernick** [comment]
See #80

**Comment by ChoHtetDev** [comment]
@brianwernick  sorry , is these changes already published to latest version ?
