### ISSUE TITLE
Repeat Mode ?

### ISSUE THREAD

**Issue by muhammadalkady** [brianwernick/PlaylistCore#89]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
 How to change repeat mode ?! I can not find a way to do it ?!
 
 Thanks

**Comment by brianwernick** [comment]
I realize this question is old however I'm still answering it as documentation for others

There isn't a built-in way to handle repeat functionality however you can provide this functionality yourself by extending the [DefaultPlaylistHandler.getNextPlayableItem()](https://github.com/brianwernick/PlaylistCore/blob/138b4c32f68b3ff4bb9db4ed2e0253f087e6923d/library/src/main/kotlin/com/devbrackets/android/playlistcore/components/playlisthandler/DefaultPlaylistHandler.kt#L469) to check for your custom repeat mode flag (e.g. single-item or full playlist) and return either the item for repeat or the next item
