### ISSUE TITLE
MediaControls togglePlayPause notification will fire twice per click

### ISSUE THREAD

**Issue by asika32764** [brianwernick/PlaylistCore#94]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - PlaylistCore version: `2.1.0`
 - Device OS version: `12`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy Tab A8`
 
###### Reproduction Steps

Add this code for logging actions, I extends a `PlaylistHandler` from `DefaultPlaylistHandler`:

```
    @Override
    public void togglePlayPause() {
        Log.i("togglePlayPause", "Pause will fire twice per click");

        if (isPlaying()) {
            pause(false);
        } else {
            play();
        }
    }
```

Click on pause button of Android lock screen MediaControls.

See Video

(video deleted)

  

###### Expected Result

Music should pause. The log should only show once.

###### Actual Result

Music paused but replay instantly. And the log shows twice.

------

I see there is a PR https://github.com/brianwernick/PlaylistCore/pull/93 to handle MediaControls functions. But currently this package has not release new version including that PR.

Is there any way I can override existing classes to fix this issue for instantly use?

**Comment by brianwernick** [comment]
I'm unable to reproduce this in the demo app using emulators with API 31 & API 32 using the 2.1.0 code base. Have you verified that this occurs in the demo app (either `master` or from the `2.1.0` tag)? If so, this appears to be a device specific issue so I'll need your help to track down what is happening.

**Comment by asika32764** [comment]
I will try to upload a demo app to Github.

**Comment by asika32764** [comment]
I resolved this issue, this bug not belongs to this project.

I'll close this issue.

Thanks.
