### ISSUE TITLE
Update to AndroidX and remove jetifier

### ISSUE THREAD

**Issue by ghenry22** [brianwernick/PlaylistCore#95]
- [X ] I have verified there are no duplicate active or recent bugs, questions, or requests

With exomedia lib being updated for AndroidX it would be awesome if you have the chance to also update playlistcore to use the androidX libraries and disable jetifier.

Then we can use these two libs together in an app without having to revert to enabling jetifier to handle old support libraries.
 
###### Reproduction Steps
search for android.support in this repo to see most of the old support library imports

###### Expected Result
don't find any old support library imports or uses

###### Actual Result
find several as this plugin has not been updated for AndroidX libs

**Comment by brianwernick** [comment]
Jetifier is enabled currently due to the ExoMedia 4.x version (possibly an older version) which included support library references. As you've pointed out, with ExoMedia 5.x this is not the case anymore, so we can now remove jetifier (after updating ExoMedia)

**Comment by brianwernick** [comment]
Jetifier was removed with #96

**Comment by ghenry22** [comment]
@brianwernick thanks for actioning this, could you possibly release a new version of playlist core?  There are a few bits that have been merged since the last release.

Thanks!

**Comment by brianwernick** [comment]
Yep, I'll work on publishing an update later this week.
